//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDelete {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebReportStyle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public WebReportStyle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureDelete.WebReportStyle", typeof(WebReportStyle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Normal {
        ///	border-bottom: thin solid #3F5280;
        ///	border-bottom-style: none;
        ///	font-family: Arial, Helvetica, sans-serif;
        ///}
        ///
        ///.Header {
        ///	font-family: &quot;Times New Roman&quot;, Times, serif;
        ///	font-size: xx-large;
        ///	color: #40526F;
        ///	margin-bottom: 1px;
        ///}
        ///.Subheader {
        ///	font-family: Arial, Helvetica, sans-serif;
        ///	font-size: large;
        ///	color: #000000;
        ///	margin-top: 1px;
        ///	margin-left:2px;
        ///}
        ///.Subtitle {
        ///	border-bottom: thin solid #3F5280;
        ///	font-family: &quot;Times New Roman&quot;, Times, serif;
        ///	font-size: x-large;
        ///	c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HTMLReportStyle {
            get {
                return ResourceManager.GetString("HTMLReportStyle", resourceCulture);
            }
        }
    }
}
