//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginWizard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginWizard.SourceCode", typeof(SourceCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Drawing;
        ///using System.Text;
        ///using System.Windows.Forms;
        ///
        ///namespace %ProjectName%
        ///{
        ///	public partial class %DialogName% : Form
        ///	{
        ///		public %DialogName%()
        ///		{
        ///			InitializeComponent();
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace %ProjectName%
        ///{
        ///	partial class %DialogName%
        ///	{
        ///		/// &lt;summary&gt;
        ///		/// Required designer variable.
        ///		/// &lt;/summary&gt;
        ///		private System.ComponentModel.IContainer components = null;
        ///
        ///		/// &lt;summary&gt;
        ///		/// Clean up any resources being used.
        ///		/// &lt;/summary&gt;
        ///		/// &lt;param name=&quot;disposing&quot;&gt;true if managed resources should be disposed; otherwise, false.&lt;/param&gt;
        ///		protected override void Dispose(bool disposing)
        ///		{
        ///			if (disposing &amp;&amp; (components != null))
        ///			{
        ///				components.Dispose();
        ///			} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DialogDesigner {
            get {
                return ResourceManager.GetString("DialogDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DialogResource {
            get {
                return ResourceManager.GetString("DialogResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.IO;
        ///using SecureDelete;
        ///using System.Xml.Serialization;
        ///using SecureDelete.WipeObjects;
        ///using SecureDelete.WipePlugin;
        ///
        ///namespace %ProjectName%
        ///{
        ///	[Plugin(&quot;%Guid%&quot;, &quot;%Name%&quot;, &quot;%Description%&quot;, %MajorVersion%, %MinorVersion%, Author = &quot;%Author%&quot;)]
        ///	class %PluginName% : IPlugin
        ///	{
        ///		%OptionsDialogFields%
        ///
        ///		public IWipeObject[] GetWipeObjects()
        ///		{
        ///			throw new Exception(&quot;Not implemented.&quot;);
        ///		}
        ///
        ///		public bool  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
    }
}
